apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-nlpf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-nlpf
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-nlpf
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-nlpf
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-nlpf
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/push-pyxis-zucq-tenant/appstudio/dc-metro-map-nlpf@sha256:76e9a8791a32581a49cbe5ea2042ffa213d42379ff76144c81d78179367ce695
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
