apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-37hx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-37hx
    app.kubernetes.io/part-of: appstudio
  name: devfile-sample-python-basic-37hx
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: devfile-sample-python-basic-37hx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: devfile-sample-python-basic-37hx
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/push-pyxis-zucq-tenant/appstudio/devfile-sample-python-basic-37hx@sha256:0d6dab2eb1533ef13d46e43588949d2604672841dbb7d77850f4a1ff1ba2f9b8
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
